### ISSUE TITLE
La linea di "andrea zoccatelli" è troppo lunga

### ISSUE THREAD

**Issue by AndreaIngoglia** [FI-153/Junior-Enterprise-Bergamo#6]

**Comment by FI-153** [comment]
Sti cazzi

**Comment by FI-153** [comment]
Scherzo, se invece di "Vicepresidente" facessimo "VP"?

**Comment by AndreaIngoglia** [comment]
Fa cagare dai ahaha


Il giorno mer 2 mar 2022 alle ore 18:49 Federico Imberti <
***@***.***> ha scritto:

**Comment by FI-153** [comment]
Sta per Vice President, 'gnorante
